var iphonePrise = 150000;
var myBugdt = 200000;
if (iphonePrise < myBugdt) {
  console.log("Buy a iphone");
}
//

var iphonePrise = 150000;
var myBugdt = 100000;
if (iphonePrise < myBugdt) {
  console.log("Buy a iphone");
} else {
  console.log("I Can't buy iphone");
}

//

var chikenprise = 180;
var myMony = 180;

if (chikenprise <= myMony) {
  console.log("I will eat chiken");
} else {
  console.log("I will not eat chiken,");
}

//

var chikenprise = 180;
var myMony = 160;

if (chikenprise <= myMony) {
  console.log("I will eat chiken");
} else {
  console.log("I will not eat chiken, I will eat poteto!");
}
